


class DataIngestionArtifact:... #3 dots means pass
class DataValidationArtifact:...
class DataTrasformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...